name: Test

on:
  push:
    paths:
      - 'weblate_schemas/**'
      - '*.py'
      - 'requirements*.txt'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'weblate_schemas/**'
      - '*.py'
      - 'requirements*.txt'
      - '.github/workflows/test.yml'

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    name: Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt -r requirements-test.txt
    - name: Test
      run: |
        py.test --cov=weblate_schemas weblate_schemas
    - name: Coverage
      run: |
        coverage xml
    - uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        flags: unittests
        name: Tests Python ${{ matrix.python-version }}
    - name: DeepSource
      continue-on-error: true
      env:
        DEEPSOURCE_DSN: https://bf0f63ba38be46a399ad6301593ae7d6@deepsource.io
      run: |
        curl https://deepsource.io/cli | sh
        ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
